#!/usr/local/bin/python
# coding: latin-1
course = 'FisicaComputacional2017'
exported = '2017-04-28T14:58:03.128Z'
assignments = ['Aula03.04.2017','Aula06.03.2017','Aula10.04.2017','aula13.03','Aula17.04.2017','Aula20.03.2017','Aula24.04.2017','Aula27.03.2017']
students = [
    {'name':'Amanda Rosa', 'email':'arosa0211@gmail.com', 'grades':['0','1','','1','','0','','1']},
    {'name':'Amanda Sasse', 'email':'amanda_sasse@aluno.ibb.unesp.br', 'grades':['0','1','','1','','0','','1']},
    {'name':'Andre Silva', 'email':'afs090996@hotmail.com', 'grades':['0','1','','1','','1','','1']},
    {'name':'Caio Garcia', 'email':'caio_garcia_souza@hotmail.com', 'grades':['0','1','','1','','1','','1']},
    {'name':'Carlos Natal', 'email':'crnjunior93@aluno.ibb.unesp.br', 'grades':['1.0','1','','1','','1','','1']},
    {'name':'Carol ', 'email':'caarolpiovesan@gmail.com', 'grades':['0.','1','','1','0','0','','0']},
    {'name':'Diogo Godoi', 'email':'godoi-dh@bol.com.br', 'grades':['0.5','1','','1','','1','','1']},
    {'name':'Eduardasilva ', 'email':'eduarda.pio.costa@aluno.ibb.unesp.br', 'grades':['0.','1','','1','0','1','','1']},
    {'name':'Felipe Breve', 'email':'brevefelipe@aluno.ibb.unesp.br', 'grades':['0','1','','1','','0','','1']},
    {'name':'Felipe Chimin', 'email':'flpchimin@aluno.ibb.unesp.br', 'grades':['1','1','','1','','1','','1']},
    {'name':'Gabriel Arruda', 'email':'gabrielaugusto.arruda@gmail.com', 'grades':['1','1','','1','','1','','1']},
    {'name':'Gabriel de Castro', 'email':'gabriel.lic.fisica@gmail.com', 'grades':['0','1','','1','','1','','1']},
    {'name':'Gustavo Henrique Tomanik', 'email':'gutomanik@gmail.com', 'grades':['0','1','','1','','1','','1']},
    {'name':'Isabella Velloso', 'email':'bella.arrigo@aluno.ibb.unesp.br', 'grades':['0','1','','1','','1','','1.0']},
    {'name':'Jhenefer Bortoleti', 'email':'jhe_bortoletio@aluno.ibb.unesp.br', 'grades':['0','1','','1','','1','','1']},
    {'name':'Juan Costa', 'email':'juan.costaa@icloud.com', 'grades':['0','1','','1','','1','','1']},
    {'name':'Julia Correa', 'email':'julia.wgcorrea@gmail.com', 'grades':['0','1','','1','','1','','0']},
    {'name':'Karoline Cafisso', 'email':'karolinecafisso@gmail.com', 'grades':['0.5','1','','1','','0','','1']},
    {'name':'Leandro do Nascimento', 'email':'leandroh123@gmail.com', 'grades':['0.5','1','','1','','1','','1']},
    {'name':'Letícia Godoi', 'email':'leticiafgodoi@gmail.com', 'grades':['0','1','','1','','1','','0']},
    {'name':'Lorraine Letiele', 'email':'lorraine.3110@aluno.ibb.unesp.br', 'grades':['0.5','1','','1','','1','','1']},
    {'name':'Lucas ', 'email':'faconi_@hotmail.com', 'grades':['0','1','','1','','0','','1']},
    {'name':'Lucas Portes Lima', 'email':'lucaslima_568@aluno.ibb.unesp.br', 'grades':['0','1','','1','','1','','1']},
    {'name':'Luiz Oliveira', 'email':'luizmiguel.hunter@gmail.com', 'grades':['1.0','1','','1','','1','','1']},
    {'name':'Natasha Marques', 'email':'natasha_policei@hotmail.com', 'grades':['0','1','','1','','1','','1']},
    {'name':'Paulo Rombaldi', 'email':'paulorombaldi@aluno.ibb.unesp.br', 'grades':['0','1','','1','','1','','0']},
    {'name':'Paulo Zago Leonel', 'email':'paulo.z.l@aluno.ibb.unesp.br', 'grades':['0.5','1','','1','','1','','1']},
    {'name':'Thales Hungaro', 'email':'thaleshungaro@gmail.com', 'grades':['0','1','','1','','1','','0']},
    {'name':'Thiago Souza Dias', 'email':'thisouzadias@aluno.ibb.unesp.br', 'grades':['0','1','','1','','1','','1']},
    {'name':'Vanessa Ulisses', 'email':'vanfilha@gmail.com', 'grades':['1','1','','1','','1.0','','1']},
    {'name':'abner alves', 'email':'alvesabner.oliveira@aluno.ibb.unesp.br', 'grades':['0','1','','1','','1','','1.0']},
    {'name':'alexandre nogueira', 'email':'alnds.90@aluno.ibb.unesp.br', 'grades':['0','1','','1','','0','','1']},
    {'name':'gustavo jarola', 'email':'gusta.vo_77@aluno.ibb.unesp.br', 'grades':['0','1','','1','','1','','1']},
    {'name':'iury goulart da fonseca', 'email':'iury_gularti@aluno.ibb.unesp.br', 'grades':['0','1','','1','','1','','1']},
    {'name':'karinacassu ', 'email':'karinagdc@aluno.ibb.unesp.br', 'grades':['1','1','','1','','1','','1']},
    {'name':'kerolyn ', 'email':'keeh.moda@aluno.ibb.unesp.br', 'grades':['0','1','','1','','0','','1.0']},
    {'name':'murilo tireli', 'email':'murilo_tirelli@hotmail.com', 'grades':['0','1','','1','','1','','1.0']},
    {'name':'tiago moura', 'email':'ttiagomouraa@aluno.ibb.unesp.br', 'grades':['0','1','','1','','0','','0']},
]
